# Generated by Django 5.0.1 on 2024-08-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localuser',
            name='age',
            field=models.IntegerField(default=20, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='localuser',
            name='name',
            field=models.CharField(max_length=24, verbose_name='이름'),
        ),
    ]
